import {usePreference} from '@aiq/ui';
import {useState,useEffect} from 'react';
import type {Workspace} from '@aiq/core';
import {unitFactor,orderBoards,overallBounds} from '@aiq/core';
import type {ExportAnnotation,EditorResult} from '@aiq/contracts';
import {AnnotationColor,Button,Card,Field,Segments,useEditor,EditorFeedback} from '@aiq/ui';
import {BoardTargets,boardTargets,resolveBoardTargets} from '@aiq/ui';
import type {BoardSelectionMode} from '@aiq/ui';
type AnnotationTarget='artboards'|'objects'|'gap';
export function AnnotationPanel({workspace}:{workspace:Workspace}) {
 const e=useEditor(workspace,'selection',{autoRefresh:true}),[target,setTarget]=usePreference<AnnotationTarget>(workspace,'annotation.target','artboards'),[mode,setMode]=usePreference<BoardSelectionMode>(workspace,'annotation.mode','active'),[pages,setPages]=useState<number[]>([]);
 const [horizontal,setHorizontal]=usePreference(workspace,'annotation.horizontal',true),[vertical,setVertical]=usePreference(workspace,'annotation.vertical',true),[fontSize,setFontSize]=usePreference(workspace,'annotation.fontSize','10'),[offset,setOffset]=usePreference(workspace,'annotation.offset','5'),[bleed,setBleed]=usePreference(workspace,'annotation.bleed','0'),[showSize,setShowSize]=useState(false);
 const [linkToObjects,setLinkToObjects]=usePreference(workspace,'annotation.linkToObjects',false);
 const [storedOptions,setOptions]=usePreference<ExportAnnotation>(workspace,'annotation.options',{enabled:true,size:true,resolution:false,colors:false,bleed:false,position:'bottom-left',offset:0,decimals:4,area:false,remark:'',autoFont:false});
 const options={...storedOptions,decimals:typeof storedOptions.decimals==='number'&&Number.isInteger(storedOptions.decimals)&&storedOptions.decimals>=0&&storedOptions.decimals<=5?storedOptions.decimals:4};
 const [curveFrom,setCurveFrom]=usePreference(workspace,'annotation.curveFrom',''),[curveTo,setCurveTo]=usePreference(workspace,'annotation.curveTo',''),[curveLabel,setCurveLabel]=usePreference(workspace,'annotation.curveLabel',true),[curveResult,setCurveResult]=useState<string|null>(null);
 const doc=e.state?.docSessionId;useEffect(()=>{setPages([]);setCurveResult(null);},[doc]);
 const unit=e.state?.rulerUnit,boards=orderBoards(e.state?.artboards??[],'horizontal'),active=e.state?.activeArtboard??0,targets=boardTargets(boards,active,mode,pages,e.state?.selectedArtboards),factor=unit?unitFactor(unit):1;
 const box=target==='objects'&&e.state?.objects.length?overallBounds(e.state.objects):e.state?.artboards[active]?.bounds;
 const selectedCount=e.state?.objects.length??0;
 const measureCurve=(from?:number,to?:number)=>{setCurveResult(null);void e.act({type:'path-length',from,to,label:curveLabel,linkToObjects:curveLabel&&linkToObjects,fontSize:Number(fontSize),annotation:{...options,enabled:true,offset:0}}).then((r:EditorResult|undefined)=>{if(r&&r.pathLength!==undefined&&unit)setCurveResult(`${(r.pathLength/factor).toFixed(options.decimals)} ${unit}`);});};
 return <><EditorFeedback message={e.message} error={e.error}/>
 <Segments label="标注对象" value={target} onChange={setTarget} options={[["artboards","画板规格"],["objects","对象尺寸"],["gap","间隙标注"]]}/>
 <div className="wb-measure-hint"><button aria-expanded={showSize} title="画板当前范围跟随 Illustrator 画板多选或活动画板。面积指对象边界宽×高，不等于路径净填充面积；正距离向外，负距离向内。" onClick={()=>setShowSize(!showSize)}>▣ 当前画板 {active+1}</button>{showSize&&<div role="status">{box?`${((box[2]-box[0])/factor).toFixed(options.decimals)} × ${((box[3]-box[1])/factor).toFixed(options.decimals)} ${unit??''}`:'没有可读取的尺寸'}</div>}</div>
 {target==='artboards'?<Card title="标注范围" icon="doc"><BoardTargets boards={boards} active={active} mode={mode} onMode={setMode} custom={pages} onCustom={setPages} selected={e.state?.selectedArtboards} selectionError={e.state?.artboardSelectionError}/></Card>
 :target==='objects'?<Card title="尺寸线" icon="size" help="宽度／高度标注沿对象边界绘制。"><p className="wb-inline-note">已选择 {selectedCount} 个对象。</p><div className="wb-scope-options"><label className="wb-check"><input type="checkbox" checked={horizontal} onChange={v=>setHorizontal(v.target.checked)}/>宽度标注</label><label className="wb-check"><input type="checkbox" checked={vertical} onChange={v=>setVertical(v.target.checked)}/>高度标注</label></div></Card>
 :<Card title="间隙标注" icon="size" help="在画布选择两个对象，标注两者之间的间距；重叠时数值为负。"><p className="wb-inline-note">当前已选 {selectedCount} 个对象{selectedCount===2?' ✓':''}。</p><div className="wb-scope-options"><label className="wb-check"><input type="checkbox" checked={vertical} onChange={v=>setVertical(v.target.checked)}/>垂直间隙</label><label className="wb-check"><input type="checkbox" checked={horizontal} onChange={v=>setHorizontal(v.target.checked)}/>水平间隙</label></div></Card>}
 <Card title="标注内容" icon="text"><div className="wb-annotation-pair wb-annotation-style"><AnnotationColor label="颜色" value={options.color??'#2364c8'} onChange={color=>setOptions({...options,color})}/><Field label="小数位数"><select className="aiq-select" aria-label="标注小数位数" value={options.decimals} onChange={v=>setOptions({...options,decimals:Number(v.target.value)})}>{[0,1,2,3,4,5].map(n=><option key={n} value={n}>{n===0?'0（整数）':'0.'+'0'.repeat(n)}</option>)}</select></Field></div>
 {target!=='gap'&&<div className="wb-scope-options">{(['size','resolution','colors','bleed','area'] as const).map(k=><label key={k}><input type="checkbox" checked={!!options[k]} onChange={v=>setOptions({...options,[k]:v.target.checked})}/>{({size:'长 × 宽',resolution:'栅格效果 ppi',colors:'色值与色块',bleed:'出血要求',area:'边界面积'})[k]}</label>)}</div>}
 <Field label="备注"><textarea rows={2} className="aiq-input wb-annotation-remark" aria-label="标注备注" maxLength={500} value={options.remark??''} onChange={v=>setOptions({...options,remark:v.target.value})}/></Field>

 {target==='artboards'&&<Segments label="标注位置" value={options.position} onChange={position=>setOptions({...options,position})} options={[["top-left","左上"],["top-right","右上"],["bottom-left","左下"],["bottom-right","右下"],["top-center","中上"],["bottom-center","中下"],["left-center","左中"],["right-center","右中"]]}/>}
 <div className="wb-annotation-pair"><Field label={`距离 ${unit??'文档单位'}`}><input aria-label="标注距离" className="aiq-input" value={offset} onChange={v=>setOffset(v.target.value)}/></Field><Field label="标注字号 pt"><div className="wb-input-reset"><input aria-label="标注字号" className="aiq-input" value={fontSize} onChange={v=>{setFontSize(v.target.value);setOptions({...options,autoFont:false});}}/><Button aria-pressed={!!options.autoFont} title="根据目标画板宽度与实际文字宽度自动适配字体字号" onClick={()=>setOptions({...options,autoFont:!options.autoFont})}>自动</Button></div></Field></div>
 {options.bleed&&<Field label={`出血要求 ${unit??'文档单位'}`}><input className="aiq-input" value={bleed} onChange={v=>setBleed(v.target.value)}/></Field>}</Card>
 {<Card title="标注关联" icon="size"><label className="wb-check" title="标注完成后与对象进入同一个群组，移动对象时标注跟随；对象在剪切蒙版内时无法关联"><input type="checkbox" checked={linkToObjects} onChange={v=>setLinkToObjects(v.target.checked)}/>关联对象群组</label><div className="aiq-row"><Button title="删除所选对象附近已生成的 AIQ 标注；关联群组会还原对象位置" disabled={e.busy||!selectedCount} onClick={()=>void e.act({type:'annotate-remove',annotation:{...options,offset:Number(offset)*factor}})}>取消标注</Button></div></Card>}
 <Card title="曲线标注" icon="size" help="先选中路径，再计算整条长度；区间仅支持单一路径，按锚点编号（从 1 开始，闭合路径可环绕）。暂不支持点击曲线上任意两点或长按拖动测量。"><div className="aiq-row"><Button disabled={e.busy||selectedCount!==1} onClick={()=>measureCurve()}>快速计算曲线</Button><Button disabled={e.busy||selectedCount!==1||!curveFrom.trim()||!curveTo.trim()} title="计算两个锚点之间的曲线段长度" onClick={()=>measureCurve(Number(curveFrom),Number(curveTo))}>曲线段尺寸</Button></div><div className="wb-annotation-pair"><Field label="起点锚点"><input className="aiq-input" aria-label="起点锚点编号" inputMode="numeric" value={curveFrom} onChange={v=>setCurveFrom(v.target.value)} placeholder="如 1"/></Field><Field label="终点锚点"><input className="aiq-input" aria-label="终点锚点编号" inputMode="numeric" value={curveTo} onChange={v=>setCurveTo(v.target.value)} placeholder="如 5"/></Field></div><label className="wb-check"><input type="checkbox" checked={curveLabel} onChange={v=>setCurveLabel(v.target.checked)}/>在曲线中点生成标注文字</label>{curveResult&&<p role="status">曲线长度：{curveResult}</p>}</Card>
 <Button variant="primary" disabled={e.busy||(target==='artboards'&&!targets.length)||(target==='gap'&&selectedCount!==2)} onClick={()=>void e.act(state=>{const scale=unitFactor(state.rulerUnit);if(options.color&&!/^#[\da-f]{6}$/i.test(options.color))throw Error('标注颜色须为 #RRGGBB');return {type:'annotate',target,artboardIndexes:target==='artboards'?resolveBoardTargets(state,mode,pages,orderBoards(state.artboards,'horizontal')):undefined,horizontal,vertical,fontSize:Number(fontSize),bleedPoints:Number(bleed)*scale,annotation:{...options,enabled:true,offset:Number(offset)*scale},linkToObjects:target!=='artboards'?linkToObjects:undefined};})}>生成标注</Button></>;
}
