import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import type { Workspace } from '@aiq/core';
import type { CharacterSettings, ParagraphSettings, EditorFont } from '@aiq/contracts';
import { Chevron, useAnchoredPopup, Button, Card, Field, useEditor, EditorFeedback, Segments } from '@aiq/ui';
const fields:Array<[keyof CharacterSettings,string,number[]]>=[
 ['fontSize','字号 pt',[6,8,9,10,11,12,14,18,24,30,36,48,60,72]],['leading','行高 pt',[10,12,14,16,18,20,24,30,36,48,60,72]],
 ['tracking','字距 1/1000 em',[-100,-50,-25,0,25,50,100,200]],['verticalScale','字高 %',[50,75,90,100,110,125,150,200]],
 ['horizontalScale','字宽 %',[50,75,90,100,110,125,150,200]],['opacity','不透明度 %',[0,10,25,50,75,90,100]]];
const paragraphs:Array<[keyof ParagraphSettings,string]>=[['leftIndent','左缩进 pt'],['rightIndent','右缩进 pt'],['firstLineIndent','首行缩进 pt'],['spaceBefore','段前 pt'],['spaceAfter','段后 pt'],['autoLeadingAmount','自动行高 %'],['minimumWordSpacing','最小词距 %'],['desiredWordSpacing','理想词距 %'],['maximumWordSpacing','最大词距 %'],['minimumLetterSpacing','最小字距 %'],['desiredLetterSpacing','理想字距 %'],['maximumLetterSpacing','最大字距 %'],['minimumGlyphScaling','最小字形缩放 %'],['desiredGlyphScaling','理想字形缩放 %'],['maximumGlyphScaling','最大字形缩放 %']];
const fontCache=new WeakMap<Workspace,EditorFont[]>();
const display=(v:unknown)=>typeof v==='number'?String(Number(v.toFixed(2))):v===undefined?'':String(v);
export function EditorTextPanel({workspace}:{workspace:Workspace}) {
 const e=useEditor(workspace,'properties',{autoRefresh:true});
 const pending=useRef<Array<{area:'character'|'paragraph';key:string;input:unknown;stamp?:string}>>([]),flushing=useRef(false),mounted=useRef(true);
 const [draft,setDraft]=useState<Record<string,string>>({}),[error,setError]=useState('');
 const [fonts,setFonts]=useState<EditorFont[]>(()=>fontCache.get(workspace)??[]),[fontOpen,setFontOpen]=useState(false),[search,setSearch]=useState(''),[tab,setTab]=useState<'all'|'favorites'>('all'),[favorites,setFavorites]=useState(workspace.getSettings().fontFavorites??[]),[page,setPage]=useState(0);
 const fontButton=useRef<HTMLButtonElement>(null),popup=useRef<HTMLDivElement>(null);
 const placement=useAnchoredPopup(fontOpen,fontButton,popup,300,400);
 const items=e.state?.objects.filter(o=>o.kind.startsWith('text-'))??[];
 const value=(area:'character'|'paragraph',key:string)=>{const first=items[0]?.[area]?.[key as never];return items.length&&items.every(o=>o[area]?.[key as never]===first)?display(first):'';};
 const currentFont=items.length&&items.every(o=>o.font===items[0]?.font)?items[0]?.font:null;
 const knownFont=fonts.find(f=>f.name===currentFont);
 useEffect(()=>{pending.current=[];setDraft({});setError('');},[e.state?.selectionKey]);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;pending.current=[];};},[]);
 useEffect(()=>{if(!fontOpen)return;const close=(event:Event)=>{if(!popup.current?.contains(event.target as Node)&&!fontButton.current?.contains(event.target as Node))setFontOpen(false);};const key=(event:KeyboardEvent)=>{if(event.key==='Escape')setFontOpen(false);};const resize=()=>setFontOpen(false);document.addEventListener('pointerdown',close);window.addEventListener('keydown',key);window.addEventListener('resize',resize);return()=>{document.removeEventListener('pointerdown',close);window.removeEventListener('keydown',key);window.removeEventListener('resize',resize);};},[fontOpen]);
 const flush=()=>{
  if(e.busy||flushing.current||!mounted.current)return;
  const change=pending.current.shift();if(!change)return;
  flushing.current=true;setError('');
  void e.act(fresh=>{if(change.stamp&&fresh.selectionKey!==change.stamp)throw Error('选区已改变，请在新选区重新设置');return {type:'text-format',[change.area]:{[change.key]:change.input}};}).then(r=>{if(r&&mounted.current)setDraft(d=>{const next={...d};delete next[change.area+'.'+change.key];return next;});}).finally(()=>{flushing.current=false;if(mounted.current&&pending.current.length)setDraft(d=>({...d}));});
 };
 useEffect(()=>{flush();});
 const commit=(area:'character'|'paragraph',key:string,input:unknown)=>{
  pending.current.push({area,key,input,stamp:e.state?.selectionKey});setDraft(d=>({...d}));
 };
 const number=(area:'character'|'paragraph',key:string)=>{const raw=draft[area+'.'+key];if(raw===undefined)return;if(!raw.trim()){setDraft(d=>{const next={...d};delete next[area+'.'+key];return next;});return;}const n=Number(raw);if(!Number.isFinite(n)){setError('请输入有效数值');return;}commit(area,key,n);};
 const numberField=(area:'character'|'paragraph',key:string,label:string,presets:number[]=[])=><Field key={key} label={label}><input className="aiq-input" aria-label={label} inputMode="decimal" list={'text-'+key} value={draft[area+'.'+key]??value(area,key)} placeholder={items.length?'混合':'—'} onChange={v=>setDraft(d=>({...d,[area+'.'+key]:v.target.value}))} onBlur={()=>number(area,key)} onKeyDown={v=>{if(v.nativeEvent.isComposing||v.keyCode===229)return;if(v.key==='Enter')v.currentTarget.blur();if(v.key==='Escape'){setDraft(d=>{const next={...d};delete next[area+'.'+key];return next;});}}}/>{presets.length>0&&<datalist id={'text-'+key}>{presets.map(n=><option key={n} value={n}/>)}</datalist>}</Field>;
 const loadFonts=async(force=false)=>{setFontOpen(true);if(!force&&fonts.length)return;const r=await e.act({type:'fonts'});if(r?.fonts){fontCache.set(workspace,r.fonts);setFonts(r.fonts);}};
 const filtered=fonts.filter(f=>(tab==='all'||favorites.includes(f.name))&&(f.family+' '+f.style+' '+f.name).toLowerCase().includes(search.toLowerCase()));
 const star=(name:string)=>{const next=favorites.includes(name)?favorites.filter(f=>f!==name):[...favorites,name];setFavorites(next);workspace.updateSettings({fontFavorites:next});};
 return <div className="wb-text-panel">
  <Button disabled={e.busy} onClick={()=>void e.read()}>读取所选文字</Button><Card title="字体与字符" icon="text">
   <button ref={fontButton} className="aiq-select wb-font-combo" aria-label="当前字体" aria-haspopup="dialog" aria-expanded={fontOpen} disabled={e.busy} title={currentFont??'选择文字后设置字体'} onClick={()=>fontOpen?setFontOpen(false):void loadFonts()}><span>{knownFont?knownFont.family+' · '+knownFont.style:currentFont??(items.length?'混合字体':'选择字体')}</span><Chevron/></button>
   {fontOpen&&createPortal(<div ref={popup} className="wb-font-popover" role="dialog" aria-label="字体库" style={placement.style} data-placement={placement.side}><input autoFocus className="aiq-input" aria-label="搜索字体" placeholder="搜索字体、家族或款式" value={search} onChange={v=>{setSearch(v.target.value);setPage(0);}}/><Segments label="字体分类" value={tab} onChange={v=>{setTab(v);setPage(0);}} options={[["all","全部字体"],["favorites","收藏"]]}/><div className="wb-font-list">{filtered.slice(page*60,(page+1)*60).map(f=><div className="wb-font-row" key={f.name}><button className="aiq-button" title={f.name} disabled={e.busy} onClick={()=>{setFontOpen(false);commit('character','font',f.name);}}><span style={{fontFamily:JSON.stringify(f.family)}}>{f.family}</span><small>{f.style}</small></button><button className="aiq-button" aria-label={(favorites.includes(f.name)?'取消收藏字体 ':'收藏字体 ')+f.name} onClick={()=>star(f.name)}>{favorites.includes(f.name)?'★':'☆'}</button></div>)}{!filtered.length&&<p>无匹配字体</p>}</div><div className="aiq-row"><Button disabled={!page} onClick={()=>setPage(page-1)}>上一页</Button><Button disabled={(page+1)*60>=filtered.length} onClick={()=>setPage(page+1)}>下一页</Button><Button disabled={e.busy} onClick={()=>void loadFonts(true)}>更新字体库</Button></div></div>,document.body)}
   <div className="wb-text-fields">{fields.map(([key,label,presets])=>numberField('character',key,label,presets))}
    <Field label="上标 / 下标"><select className="aiq-select" aria-label="上标下标" disabled={e.busy} value={value('character','baseline')} onChange={v=>commit('character','baseline',v.target.value)}><option value="" disabled>混合 / 未选择</option><option value="normal">正常</option><option value="super">上标</option><option value="sub">下标</option></select></Field>
    <Field label="自动行高"><select className="aiq-select" aria-label="自动行高" disabled={e.busy} value={value('character','autoLeading')} onChange={v=>commit('character','autoLeading',v.target.value==='true')}><option value="" disabled>混合 / 未选择</option><option value="true">开启</option><option value="false">关闭</option></select></Field>
   </div><details><summary>基线偏移</summary>{numberField('character','baselineShift','基线偏移 pt',[-6,-3,0,3,6,12])}</details>
  </Card>
  <Card title="段落" icon="text"><div className="wb-paragraph-alignment" role="group" aria-label="段落对齐">{([['left','左对齐'],['center','居中'],['right','右对齐'],['full-left','两端对齐，末行左对齐'],['full-center','两端对齐，末行居中'],['full-right','两端对齐，末行右对齐'],['full','全部两端对齐']] as const).map(([key,label])=><Button key={key} title={label} aria-label={label} aria-pressed={value('paragraph','justification')===key} disabled={e.busy||!items.length} onClick={()=>commit('paragraph','justification',key)}><ParagraphIcon mode={key}/></Button>)}</div><div className="wb-paragraph-lists" role="group" aria-label="段落标记">{([['bullet','项目符号','添加可编辑项目符号'],['number','段落编号','按所选段落生成可编辑编号'],['clear','清除段落标记','清除行首项目符号或编号']] as const).map(([mode,label,hint])=><Button key={mode} title={hint} aria-label={label} disabled={e.busy||!items.length} onClick={()=>void e.act({type:'text-list',mode})}><svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5"><path d="M9 5h13M9 12h13M9 19h13"/>{mode==='bullet'?[5,12,19].map(y=><circle key={y} cx="3" cy={y} r="1.5" fill="currentColor"/>):mode==='number'?<g stroke="none" fill="currentColor" fontSize="8"><text x="1" y="7">1</text><text x="1" y="15">2</text><text x="1" y="23">3</text></g>:<path d="m1 9 5 6m0-6-5 6"/>}</svg></Button>)}<span className="wb-help" tabIndex={0} title="直接添加可编辑的行首文字。需要原生自动续号时，使用下方更多段落设置。" aria-label="段落标记说明">?</span></div><details><summary>缩进与间距</summary><div className="wb-text-fields">{paragraphs.map(([key,label])=>numberField('paragraph',key,label))}{(['hyphenation','everyLineComposer'] as const).map(key=><Field key={key} label={key==='hyphenation'?'自动断字':'多行排版器'}><select className="aiq-select" disabled={e.busy} value={value('paragraph',key)} onChange={v=>commit('paragraph',key,v.target.value==='true')}><option value="" disabled>混合</option><option value="true">开启</option><option value="false">关闭</option></select></Field>)}</div></details><Button disabled={e.busy||!e.state?.nativeCommands?.includes('paragraph-panel')} onClick={()=>void e.act({type:'native',command:'paragraph-panel'})}>原生段落更多设置…</Button></Card>
  <EditorFeedback message={e.message} error={error||e.error}/>
  <details><summary>大小写与转曲</summary><div className="wb-text-fields"><Field label="大小写"><select className="aiq-select" aria-label="大小写" disabled={e.busy} value="" onChange={v=>void e.act({type:'text-case',mode:v.target.value as 'upper'|'lower'|'title'|'sentence'})}><option value="" disabled>选择并应用</option>{[['upper','全部大写'],['lower','全部小写'],['title','每词首字母大写'],['sentence','句首大写']].map(([v,l])=><option key={v} value={v}>{l}</option>)}</select></Field><Field label="文字转曲"><select className="aiq-select" aria-label="文字转曲" disabled={e.busy} value="" onChange={v=>void e.act({type:'outlines',scope:v.target.value as 'selection'|'document'})}><option value="" disabled>选择范围并转曲</option><option value="selection">所选文字</option><option value="document">所有可编辑文字</option></select></Field></div></details>
 </div>;
}

function ParagraphIcon({mode}:{mode:string}){return <svg aria-hidden="true" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.5">{[4,8,12,16,20].map((y,i)=>{const full=mode.startsWith('full'),width=mode==='full'||full&&i<4?20:i%2?14:18,last=full?mode.slice(5):mode,x=last==='right'?22-width:last==='center'?(24-width)/2:2;return <path key={y} d={`M${x} ${y}h${width}`}/>;})}</svg>;}
