import {useEffect,useState} from 'react';
import type {Workspace} from '@aiq/core';
import type {StyleSample,StyleField} from '@aiq/contracts';
import {Button,Card,EditorFeedback,useEditor} from '@aiq/ui';
export function StyleTransferPanel({workspace}:{workspace:Workspace}){
 const e=useEditor(workspace,'selection',{autoRefresh:true}),[sample,setSample]=useState<StyleSample|null>(null),[row,setRow]=useState(0),[fields,setFields]=useState<StyleField[]>([]);
 const doc=e.state?.docSessionId;
 useEffect(()=>{setSample(null);setFields([]);setRow(0);},[doc]);
 const active=sample&&sample.docSessionId===doc?sample.rows[row]:null;
 const choose=(index:number)=>{setRow(index);const next=sample?.rows[index];setFields(next?.fields.filter(f=>!['size','width','textFrameSize'].includes(f.key)).map(f=>f.key)??[]);};
 return <><EditorFeedback message={e.message} error={e.error}/><Card title="样式吸取" icon="select" help="选择一个对象后吸取；群组和剪贴蒙版逐个列出内部对象。样式仅保留在当前页面与文档会话。"><Button variant="primary" disabled={e.busy||e.state?.objects.length!==1} onClick={()=>void e.act({type:'style-transfer',operation:'capture'}).then(result=>{if(result?.styleSample){setSample(result.styleSample);setRow(0);setFields(result.styleSample.rows[0]?.fields.filter(f=>!['size','width','textFrameSize'].includes(f.key)).map(f=>f.key)??[]);}})}>吸取所选对象</Button><p className="wb-inline-note">点击条目查看属性，“定位”会在画布选中并强调来源对象。之后在画布选择目标，再点击赋予。</p></Card>{sample&&<Card title={`来源对象 · ${sample.rows.length} 项`} icon="select"><div className="wb-style-rows">{sample.rows.map(item=><div key={item.index} className="wb-style-row"><button className="aiq-button" aria-pressed={row===item.index} onClick={()=>{choose(item.index);void e.act({type:'style-transfer',operation:'locate',sampleToken:sample.token,row:item.index});}} style={{paddingLeft:8+Math.min(item.depth,5)*8}}>{item.name}<small>{item.kind}</small></button></div>)}</div></Card>}{active&&<Card title="选择赋予属性" icon="select"><div className="wb-style-fields">{active.fields.map(field=><label className="wb-check" key={field.key}><input type="checkbox" checked={fields.includes(field.key)} onChange={event=>setFields(old=>event.target.checked?[...old.filter(k=>!(['size','width','textFrameSize'].includes(field.key)&&['size','width','textFrameSize'].includes(k))),field.key]:old.filter(k=>k!==field.key))}/><span>{field.label}<small>{field.value}</small></span></label>)}</div>{active.warnings.map((warning,i)=><p className="wb-inline-note" key={i}>{warning}</p>)}<p className="wb-inline-note">逐项属性不包含效果面板中的多重外观。图像本体没有填充／描边时，请吸取其外框或蒙版路径。群组目标会逐个应用到可编辑子对象。</p><Button variant="primary" disabled={e.busy||!fields.length||!e.state?.objects.length} onClick={()=>void e.act({type:'style-transfer',operation:'apply',sampleToken:sample!.token,row,fields})}>赋予所选目标</Button></Card>}</>;
}
