import {useState} from 'react';
import type {Workspace} from '@aiq/core';
import {Button,Field,EditorFeedback} from '@aiq/ui';
export function DataSettings({workspace}:{workspace:Workspace}){
 const stored=workspace.getSettings().dataStorage;
 const [folder,setFolder]=useState(stored?.folder??''),[format,setFormat]=useState<'zip'|'aiqsettings'>(stored?.format??'zip'),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const status=workspace.getSettingsStorageStatus();
 return <section className="aiq-card"><h3 className="aiq-card-title">设置数据</h3><Field label="保存位置" help="自动记住各工具的选项。设置文件包含工作台偏好，不包含稿件、字体、图片或选区。在所选目录下建立 AIQ-Workbench 子目录，本机保留恢复副本。"><div className="wb-dir-row"><input className="aiq-input" aria-label="设置保存位置" placeholder="默认本机用户数据目录" value={folder} onChange={e=>setFolder(e.target.value)}/><Button disabled={busy} onClick={async()=>{setError('');setBusy(true);try{const selected=await workspace.chooseFolder(folder);if(selected)setFolder(selected);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}}}>浏览</Button></div></Field><Field label="存储格式" help="ZIP 可直接解压，.aiqsettings 为可读 JSON。"><select className="aiq-select" aria-label="设置存储格式" value={format} onChange={e=>setFormat(e.target.value as typeof format)}><option value="zip">ZIP (.zip)</option><option value="aiqsettings">工作台设置 (.aiqsettings)</option></select></Field><div className="aiq-row wb-settings-storage-actions"><Button disabled={busy||!folder.trim()} onClick={()=>{try{setError('');if(!/^(?:[A-Za-z]:[\\/]|\\\\[^\\]+\\[^\\]+)/.test(folder.trim()))throw Error('请输入绝对目录');workspace.updateSettings({dataStorage:{folder:folder.trim(),format}});setMessage(workspace.getSettingsStorageStatus().warning?'':'已应用，后续选项自动保存');}catch(e){setError(e instanceof Error?e.message:String(e));}}}>应用保存位置</Button><Button disabled={busy} onClick={()=>{workspace.updateSettings({dataStorage:undefined});setFolder('');setMessage('已恢复本机默认位置');}}>恢复默认位置</Button></div><p className="wb-inline-note" style={{overflowWrap:'anywhere'}}>当前：{status.location}</p>{status.warning&&<p role="alert">{status.warning}</p>}<EditorFeedback message={message} error={error}/></section>;
}
