import {useState} from 'react';
import {Button,Card,Field,EditorFeedback,usePreference} from '@aiq/ui';
import type {Workspace} from '@aiq/core';
import {runWorkbenchUpdate,type UpdateResult} from '@aiq/host-adapter';
export function UpdateSettings({workspace}:{workspace:Workspace}){
 const [channel,setChannel]=usePreference<'github'|'mirror'>(workspace,'update.channel','github'),[mirror,setMirror]=usePreference(workspace,'update.mirror',''),[result,setResult]=useState<UpdateResult|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const run=async(operation:'check'|'install')=>{setBusy(true);setError('');try{const r=await runWorkbenchUpdate(operation,channel,mirror.trim());setResult(r);setMessage(r.status==='checked'?(r.available?`发现版本 ${r.version}`:`当前已是最新版本 ${r.currentVersion}`):r.status==='installed'?'更新已安装，重启 Illustrator 后使用':r.status==='queued'||r.status==='waiting'?'更新已排队，将在 Illustrator 正常退出后安装':`安装状态：${r.status} ${r.message??''}`);}catch(e){setError(e instanceof Error?e.message:String(e));}finally{setBusy(false);}};
 return <Card title="工作台更新" icon="refresh"><Field label="更新来源"><select className="aiq-select" value={channel} disabled={busy} onChange={e=>{setChannel(e.target.value as typeof channel);setResult(null);}}><option value="github">GitHub 官方仓库</option><option value="mirror">国内镜像／自建加速地址</option></select></Field>{channel==='mirror'&&<Field label="HTTPS 镜像前缀" help="镜像须支持“前缀 + 完整 GitHub 地址”。安装前核验发布者签名和 SHA-256。"><input className="aiq-input" aria-label="更新镜像地址" value={mirror} placeholder="https://你的镜像站/" onChange={e=>{setMirror(e.target.value);setResult(null);}}/></Field>}<div className="aiq-row wb-space"><Button disabled={busy} onClick={()=>void run('check')}>{busy?'正在处理…':'检查更新'}</Button><Button variant="primary" disabled={busy||!result?.available||result.status!=='checked'} onClick={()=>void run('install')}>下载并排队安装</Button></div>{result?.notes&&<p className="wb-inline-note">{result.notes}</p>}<p className="wb-inline-note">仅主动检查。安装器自动识别 Illustrator 目录；软件运行时等待正常退出，不保存或关闭稿件。</p><EditorFeedback message={message} error={error}/></Card>;
}
