import { useEffect, useRef, useState } from 'react';
import { createPortal } from 'react-dom';
import type { Workspace } from '@aiq/core';
import { Button, Segments, Chevron, useAnchoredPopup } from '@aiq/ui';
export function ExportDirectory({workspace,folder,currentFolder,alongside,busy,onChange,onChoose,onOpen}:{workspace:Workspace;folder:string;currentFolder:string;alongside:boolean;busy:boolean;onChange:(value:string)=>void;onChoose:()=>void;onOpen:()=>void}) {
 const [position,setPosition]=useState(false),[tab,setTab]=useState<'recent'|'favorites'>('recent'),[favorites,setFavorites]=useState<string[]>(()=>workspace.getSettings().exportFavorites??[]);
 const container=useRef<HTMLDivElement>(null),menu=useRef<HTMLDivElement>(null),trigger=useRef<HTMLButtonElement>(null);
 useEffect(()=>{if(!position)return;const close=(event:PointerEvent)=>{if(!container.current?.contains(event.target as Node)&&!menu.current?.contains(event.target as Node))setPosition(false);};const escape=(event:KeyboardEvent)=>{if(event.key==='Escape'){setPosition(false);trigger.current?.focus();}};const resize=()=>setPosition(false);document.addEventListener('pointerdown',close);document.addEventListener('keydown',escape);window.addEventListener('resize',resize);return()=>{document.removeEventListener('pointerdown',close);document.removeEventListener('keydown',escape);window.removeEventListener('resize',resize);};},[position]);
 const placement=useAnchoredPopup(position,container,menu,220,310);
 const paths=tab==='favorites'?favorites:[...new Set([currentFolder,...workspace.getSettings().exportFolders??[]].filter(Boolean))];
 const star=(path:string)=>{const next=favorites.includes(path)?favorites.filter(p=>p!==path):[...favorites,path];setFavorites(next);workspace.updateSettings({exportFavorites:next});};
 return <div ref={container} className="wb-export-directory"><div className="wb-dir-row"><div className="wb-address-input"><input className="aiq-input" aria-label="项目导出目录" title={currentFolder} value={alongside?currentFolder:folder} placeholder="选择或粘贴目录" disabled={alongside||busy} onChange={event=>onChange(event.target.value)}/><button ref={trigger} className="aiq-button" aria-label="最近或收藏目录" aria-expanded={!!position} disabled={busy} onClick={()=>{if(position){setPosition(false);return;}setPosition(true);}}><Chevron/></button></div><Button icon="doc" disabled={busy} onClick={onChoose}>浏览</Button><Button disabled={busy||!currentFolder} onClick={onOpen} title="打开当前目录；导出后打开实际输出目录">打开</Button></div>
 {position&&createPortal(<div ref={menu} className="wb-directory-menu wb-directory-popover" role="dialog" aria-label="目录菜单" style={placement.style} data-placement={placement.side}><Segments label="目录分类" value={tab} onChange={setTab} options={[["recent","最近"],["favorites","收藏"]]}/><p className="wb-directory-current">当前地址<span>{currentFolder||'尚未选择目录'}</span></p><div className="wb-directory-list">{paths.map(path=><div className="wb-directory-entry" key={path}><button title={path} onClick={()=>{onChange(path);setPosition(false);trigger.current?.focus();}}>{path}</button><button className="wb-star" aria-label={(favorites.includes(path)?'取消收藏 ':'收藏 ')+path} aria-pressed={favorites.includes(path)} onClick={()=>star(path)}>{favorites.includes(path)?'★':'☆'}</button></div>)}{!paths.length&&<p className="wb-inline-note">暂无收藏地址</p>}</div><Button icon="doc" onClick={()=>{setPosition(false);onChoose();}}>手动选择地址…</Button></div>,container.current!.closest('.aiq-workbench')??document.body)}</div>;
}
