import {useEffect,useMemo,useRef,useState} from 'react';
import type {Workspace} from '@aiq/core';
import type {EditorFont,VariableBinding,VariableTable,VariableTemplate,VariableResultRow,ExportProgress,VariableHeaderDirection} from '@aiq/contracts';
import {Button,Card,Field,EditorFeedback,useEditor} from '@aiq/ui';
import {buildVariablePlan,newBinding,variableLayout} from './plan.js';

function useNumberDraft(initial:number){const [draft,setDraft]=useState(String(initial));return [draft.trim()===''?NaN:Number(draft),draft,(value:number|string)=>setDraft(String(value))] as const;}
export function VariableDataPanel({workspace}:{workspace:Workspace}){
 const preferences=workspace.getSettings().variablePreferences;
 const e=useEditor(workspace,'selection',{autoRefresh:true});
 const [table,setTable]=useState<VariableTable|null>(null),[template,setTemplate]=useState<VariableTemplate|null>(null),[bindings,setBindings]=useState<VariableBinding[]>([]);
 const [file,setFile]=useState<File|null>(null),[encoding,setEncoding]=useState(preferences?.encoding??'utf-8'),[hidden,setHidden]=useState(preferences?.includeHidden??false),[loading,setLoading]=useState(false),[error,setError]=useState('');
 const [first,firstDraft,setFirst]=useNumberDraft(1),[last,lastDraft,setLast]=useNumberDraft(70),[columns,columnsDraft,setColumns]=useNumberDraft(preferences?.columns??5),[gap,gapDraft,setGap]=useNumberDraft(preferences?.horizontalGap??preferences?.gap??10),[base,setBase]=useState(preferences?.imageBase??''),[nameColumn,setNameColumn]=useState('');
 const [rowsPerBlock,rowsDraft,setRowsPerBlock]=useNumberDraft(preferences?.rowsPerBlock??10),[verticalGap,verticalGapDraft,setVerticalGap]=useNumberDraft(preferences?.verticalGap??preferences?.gap??10),[direction,setDirection]=useState<VariableHeaderDirection>(preferences?.headerDirection??'row');
 const [boardIndex,setBoardIndex]=useState<number|null>(null),[imageFiles,setImageFiles]=useState<string[]|undefined>(),[imagesLoading,setImagesLoading]=useState(false);
 const boardSession=useRef('');useEffect(()=>{const session=e.state?.docSessionId??'';if(boardSession.current!==session){boardSession.current=session;setBoardIndex(null);}},[e.state?.docSessionId]);
 const [fonts,setFonts]=useState<EditorFont[]>([]),[results,setResults]=useState<VariableResultRow[]>([]),[job,setJob]=useState(''),[running,setRunning]=useState(false),[progress,setProgress]=useState<ExportProgress|null>(null),[cancelling,setCancelling]=useState(false);
 useEffect(()=>{if(Number.isInteger(columns)&&columns>=1&&columns<=10&&Number.isInteger(rowsPerBlock)&&rowsPerBlock>=1&&rowsPerBlock<=100&&[gap,verticalGap].every(n=>Number.isFinite(n)&&n>=0&&n<=1000))workspace.updateSettings({variablePreferences:{columns,gap,imageBase:base,encoding,includeHidden:hidden,rowsPerBlock,horizontalGap:gap,verticalGap,headerDirection:direction}});},[workspace,columns,rowsPerBlock,gap,verticalGap,base,encoding,hidden,direction]);
 const fileInput=useRef<HTMLInputElement>(null);
 const worker=useRef<Worker|null>(null),importSerial=useRef(0),alive=useRef(true);
 useEffect(()=>{alive.current=true;return()=>{alive.current=false;worker.current?.terminate();};},[]);
 useEffect(()=>{if(!running||!job)return;let active=true,timer:ReturnType<typeof setTimeout>|undefined;const poll=async()=>{try{const p=await workspace.readExportProgress(job);if(active&&p)setProgress(p);}catch{/* keep last complete status */}if(active)timer=setTimeout(()=>void poll(),1000);};void poll();return()=>{active=false;clearTimeout(timer);};},[workspace,running,job]);
 const importFile=async(next:File,sheet?:string,showHidden=hidden,charset=encoding,headerDirection=direction)=>{
  const id=++importSerial.current;worker.current?.terminate();setLoading(true);setError('');setTable(null);setBindings([]);setResults([]);setNameColumn('');
  try{if(next.size>10*1024*1024)throw Error('请选择小于 10 MB 的表格');const bytes=await next.arrayBuffer();if(id!==importSerial.current||!alive.current)return;
   const w=new Worker(new URL('./table.worker.ts',import.meta.url),{type:'module'});worker.current=w;
   const done=()=>{w.terminate();if(worker.current===w)worker.current=null;};
   w.onmessage=(event:MessageEvent<{table?:VariableTable;error?:string}>)=>{if(id===importSerial.current&&alive.current){setLoading(false);if(event.data.table){setTable(event.data.table);setLast(Math.min(70,event.data.table.rows.length));setFirst(1);}else setError(event.data.error??'读取失败');}done();};
   w.onerror=()=>{if(id===importSerial.current&&alive.current){setLoading(false);setError('表格读取失败，请检查文件格式');}done();};
   w.postMessage({bytes,name:next.name,sheet,hidden:showHidden,encoding:charset,direction:headerDirection},[bytes]);
  }catch(err){if(alive.current){setLoading(false);setError(err instanceof Error?err.message:String(err));}}
 };
 const capture=async()=>{setError('');if(boardIndex===null){setError('请先选择模板画板');return;}const r=await e.act({type:'variable-data',operation:'capture',artboardIndex:boardIndex});if(r?.variableTemplate){setTemplate(r.variableTemplate);setBindings([]);setResults([]);}};
 const bindSelection=async(bindingId?:string)=>{if(!template||!table)return;setError('');const r=await e.act({type:'variable-data',operation:'bind-selection',templateToken:template.token});if(r?.variableTargetId){const target=template.targets.find(t=>t.id===r.variableTargetId);if(!target)return;if(bindingId)change(bindingId,{targetId:target.id});else{const binding=newBinding(table.columns[0]!.id,target.id,'bind-'+Date.now().toString(36)+'-'+bindings.length);if(target.kind!=='TextFrame')binding.kind='image';setBindings(list=>[...list,binding]);}}};
 const importImages=async()=>{setError('');setImagesLoading(true);try{const folder=await workspace.chooseFolder(base);if(!folder)return;const r=await e.act({type:'variable-data',operation:'images',folder});if(r?.files){setBase(r.folder??folder);setImageFiles(r.files);}}catch(err){setError(err instanceof Error?err.message:String(err));}finally{setImagesLoading(false);}};
 const change=(id:string,patch:Partial<VariableBinding>)=>setBindings(list=>list.map(b=>b.id===id?{...b,...patch}:b));
 const {plan,planError}=useMemo(()=>{
  const selectedRows=table?.rows.slice(Math.max(0,first-1),Math.max(0,last)).map(r=>r.row)??[];
  let plan:{records:ReturnType<typeof buildVariablePlan>['records'];errors:Array<{row:number;reason:string}>}={records:[],errors:[]},planError='';
  if(table&&template&&bindings.length){try{if(!Number.isInteger(first)||!Number.isInteger(last)||first<1||last<first||last>table.rows.length)throw Error('请填写有效的起始和结束记录');plan=buildVariablePlan(table,template,bindings,selectedRows,nameColumn,base,imageFiles);variableLayout(template,selectedRows.length,columns,rowsPerBlock,gap*72/25.4,verticalGap*72/25.4);}catch(err){planError=err instanceof Error?err.message:String(err);}}
  return {plan,planError};
 },[table,template,bindings,first,last,nameColumn,base,imageFiles,columns,rowsPerBlock,gap,verticalGap]);
 const generate=async(preview:boolean)=>{if(!template||planError||!plan.records.length||plan.errors.length)return;setError('');
  if(!Number.isInteger(first)||!Number.isInteger(last)||first<1||last<first||last>(table?.rows.length??0)){setError('记录范围无效');return;}
  const rows=preview?plan.records.slice(0,1):plan.records;if(JSON.stringify(rows).length>1000000){setError('本批数据超过 1 MB，请减少记录数');return;}
  const id=workspace.supportsExportProgress?.()?('vdp-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)):undefined;setJob(id??'');setProgress(null);setCancelling(false);setRunning(true);
  try{const r=await e.act({type:'variable-data',operation:preview?'preview':'generate',templateToken:template.token,bindings,rows,columns,rowsPerBlock,gap:gap*72/25.4,horizontalGap:gap*72/25.4,verticalGap:verticalGap*72/25.4,jobId:id});if(r?.variableRows)setResults(r.variableRows);if(r?.exportProgress)setProgress(r.exportProgress);}finally{if(alive.current)setRunning(false);}
 };
 return <div className="wb-vdp">
 <Card title="1 · 导入表格" icon="doc"><div className="wb-file-picker"><Button icon="doc" disabled={running||loading} onClick={()=>fileInput.current?.click()}>选择表格</Button><span title={file?.name}>{file?.name??"未选择文件"}</span></div><input ref={fileInput} hidden type="file" aria-label="导入可变数据表格" accept=".xlsx,.csv" disabled={running} onChange={v=>{const next=v.target.files?.[0];if(next){setFile(next);const path=(next as File&{path?:string}).path;if(path&&!imageFiles)setBase(path.replace(/[\\/][^\\/]*$/,''));void importFile(next);}}}/>
 <div className="wb-form-grid"><Field label="CSV 编码"><select className="aiq-select" value={encoding} disabled={running} onChange={v=>{setEncoding(v.target.value);if(file)void importFile(file,undefined,hidden,v.target.value);}}><option value="utf-8">UTF-8</option><option value="gb18030">GB18030／GBK</option></select></Field>{table&&<Field label="工作表"><select className="aiq-select" aria-label="可变数据工作表" value={table.sheet} disabled={running} onChange={v=>{if(file)void importFile(file,v.target.value);}}>{table.sheets.map(s=><option key={s}>{s}</option>)}</select></Field>}</div>
 <label className="wb-check"><input type="checkbox" checked={hidden} disabled={running} onChange={v=>{setHidden(v.target.checked);if(file)void importFile(file,table?.sheet,v.target.checked);}}/>包含隐藏行</label>
 <Field label="标题方向"><select className="aiq-select" aria-label="表格标题方向" value={direction} disabled={running||loading} onChange={v=>{const next=v.target.value as VariableHeaderDirection;setDirection(next);if(file)void importFile(file,table?.sheet,hidden,encoding,next);}}><option value="row">首行是列标题</option><option value="column">首列是标题（转置）</option></select></Field>
 {loading&&<p role="status">正在读取表格…</p>}{table&&<><p>{table.rows.length} 条记录 · {table.columns.length} 列</p>{table.warnings.map(w=><p className="wb-inline-note" key={w}>{w}</p>)}<div className="wb-vdp-table"><table><thead><tr><th>原行号</th>{table.columns.map(c=><th key={c.id}>{c.label}</th>)}</tr></thead><tbody>{table.rows.slice(first-1,Math.min(first+3,table.rows.length)).map(r=><tr key={r.row}><td>{r.row}</td>{table.columns.map(c=><td key={c.id}>{r.cells[c.id]?.error??r.cells[c.id]?.runs.map((run,i)=>run.bold?<strong key={i}>{run.text}</strong>:<span key={i}>{run.text}</span>)}</td>)}</tr>)}</tbody></table></div></>}
 </Card>
 <Card title="2 · 选择定稿模板" icon="select"><Field label="模板画板"><select className="aiq-select" aria-label="模板画板" disabled={e.busy||running} value={boardIndex??''} onChange={v=>setBoardIndex(v.target.value===''?null:Number(v.target.value))}><option value="">请选择具体画板</option>{e.state?.artboards.map(b=><option key={b.index} value={b.index}>{b.index+1} · {b.name}</option>)}</select></Field><Button disabled={e.busy||running} onClick={()=>void e.read()}>读取画板列表</Button><Button title="捕获该画板全部可见归属设计，保留完整群组、剪切结构与出血对象；文字和图片按外框确定归属。不会改动源稿或选区。" disabled={e.busy||running||boardIndex===null} onClick={()=>void capture()}>将所选画板记为模板</Button>{template&&<p>{template.docName} · {template.boardName}<br/>{template.objectCount} 个对象 · {(template.width*25.4/72).toFixed(1)} × {(template.height*25.4/72).toFixed(1)} mm</p>}</Card>
 <Card title="3 · 列与对象绑定" icon="swap"><Button title="先在模板画布上直接选中一个文字框或图片矩形，再点击此按钮并选择对应表头。组内对象可用直接选择工具选中。" disabled={!table||!template||running||e.busy} onClick={()=>void bindSelection()}>绑定画布所选对象</Button>
 {bindings.map((b,index)=><section className="wb-vdp-binding" key={b.id}><div className="wb-inline-actions"><strong>绑定 {index+1}</strong><Button disabled={running} onClick={()=>setBindings(list=>list.filter(x=>x.id!==b.id))}>移除</Button></div>
 <Field label="表格列"><select className="aiq-select" aria-label={'绑定列 '+index} disabled={running} value={b.column} onChange={v=>change(b.id,{column:v.target.value})}>{table?.columns.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field>
 <Field label="模板对象"><select className="aiq-select" aria-label={'绑定对象 '+index} disabled={running} value={b.targetId} onChange={v=>change(b.id,{targetId:v.target.value})}>{template?.targets.map(t=><option key={t.id} value={t.id}>{t.id} · {t.name||t.kind}{t.text?' · '+t.text.slice(0,24):''}</option>)}</select></Field>
 <Button disabled={running||e.busy} onClick={()=>void bindSelection(b.id)}>改用画布所选对象</Button>
 <Field label="替换内容"><select className="aiq-select" title={b.kind==='graphic'?'列中填写模板内图形的唯一名称，支持普通路径与完整群组。':b.kind==='qr'?'生成黑白矢量二维码，保留四模块留白；最小模块 0.2 mm，长方形内居中保持正方形。':undefined} aria-label={'绑定类型 '+index} value={b.kind} disabled={running} onChange={v=>change(b.id,{kind:v.target.value as VariableBinding['kind'],placeholder:'',graphicStyle:'',fill:'',opacity:undefined,size:undefined})}><option value="text">文字</option><option value="image">本地图片</option><option value="qr">二维码内容</option><option value="graphic">模板内命名图形</option><option value="fill">填色 #RRGGBB</option><option value="opacity">不透明度 0–100</option></select></Field>
 {b.kind==='text'&&<><Field label="占位符（留空替换整个文字框）"><input className="aiq-input" aria-label={'占位符 '+index} value={b.placeholder} disabled={running} onChange={v=>change(b.id,{placeholder:v.target.value})}/></Field><Field label="文字样式"><select className="aiq-select" value={b.style} disabled={running} onChange={v=>change(b.id,{style:v.target.value as VariableBinding['style']})}><option value="template">模板基础样式</option><option value="emphasis">模板样式＋表格加粗</option><option value="custom">指定样式＋表格加粗</option></select></Field>
 <Button disabled={e.busy||running} onClick={()=>void e.act({type:'fonts'}).then(r=>{if(r?.fonts)setFonts(r.fonts);})}>读取本机字体款式</Button>
 {b.style==='custom'&&<><Field label="基础字体款式"><input className="aiq-input" list="vdp-fonts" value={b.font} disabled={running} onChange={v=>change(b.id,{font:v.target.value})}/></Field><Field label="指定字号 pt（留空沿用）"><input className="aiq-input" type="number" value={b.size??''} disabled={running} onChange={v=>change(b.id,{size:v.target.value?Number(v.target.value):undefined})}/></Field><Field label="字符样式"><select className="aiq-select" value={b.characterStyle} disabled={running} onChange={v=>change(b.id,{characterStyle:v.target.value})}><option value="">沿用模板</option>{template?.characterStyles.map(s=><option key={s}>{s}</option>)}</select></Field></>}
 {b.style!=='template'&&<Field label="加粗对应字体款式"><input className="aiq-input" aria-label={'粗体款式 '+index} list="vdp-fonts" value={b.boldFont} disabled={running} placeholder="选择真实的粗体款式" onChange={v=>change(b.id,{boldFont:v.target.value})}/></Field>}
 <Field label="文字超出模板框"><select className="aiq-select" value={b.overflow} disabled={running} onChange={v=>change(b.id,{overflow:v.target.value as VariableBinding['overflow']})}><option value="error">报告该行失败</option>{!b.placeholder&&<option value="shrink">缩小到最小字号</option>}</select></Field>{b.overflow==='shrink'&&<Field label="最小字号 pt"><input className="aiq-input" type="number" value={b.minSize} disabled={running} onChange={v=>change(b.id,{minSize:Number(v.target.value)})}/></Field>}</>}
 {['image','graphic'].includes(b.kind)&&<Field label="图片与矩形适配"><select className="aiq-select" title="图片使用目标矩形作为剪切蒙版；四种模式都保持原图比例。按宽／按高超出部分裁切。" value={b.fit} disabled={running} onChange={v=>change(b.id,{fit:v.target.value as VariableBinding['fit']})}><option value="contain">等比完整显示</option><option value="cover">等比填满并裁切</option><option value="width">按宽度等比</option><option value="height">按高度等比</option></select></Field>}
 <Field label="空值处理"><select className="aiq-select" value={b.empty} disabled={running} onChange={v=>change(b.id,{empty:v.target.value as VariableBinding['empty']})}><option value="error">报告该行失败</option><option value="keep">保留模板内容</option>{b.kind==='text'&&<option value="clear">清空绑定文字</option>}</select></Field>
 {b.kind!=='qr'&&!b.placeholder&&<><Field label="对象图形样式"><select className="aiq-select" value={b.graphicStyle} disabled={running} onChange={v=>change(b.id,{graphicStyle:v.target.value})}><option value="">沿用模板</option>{template?.graphicStyles.map(s=><option key={s}>{s}</option>)}</select></Field><div className="wb-form-grid"><Field label="不透明度 %（留空沿用）"><input className="aiq-input" type="number" value={b.opacity??''} disabled={running} onChange={v=>change(b.id,{opacity:v.target.value?Number(v.target.value):undefined})}/></Field><Field label="填色（留空沿用）"><input className="aiq-input" value={b.fill} disabled={running} placeholder="#RRGGBB" onChange={v=>change(b.id,{fill:v.target.value})}/></Field></div></>}
 </section>)}<datalist id="vdp-fonts">{fonts.map(f=><option key={f.name} value={f.name}>{f.family} · {f.style}</option>)}</datalist></Card>
 <Card title="4 · 检查与生成" icon="check"><div className="wb-inline-actions"><Button title="选择系统目录；表格图片列填写准确文件名或唯一名称，不按文件排列顺序绑定。" disabled={running||e.busy||imagesLoading} onClick={()=>void importImages()}>{imagesLoading?'正在读取目录…':'导入图片目录'}</Button>{imageFiles&&<span>{imageFiles.length} 张图片 · 按名称匹配</span>}</div><Field label={imageFiles?'已导入图片目录':'相对图片路径的基准目录'}><input className="aiq-input" value={base} disabled={running} onChange={v=>{setBase(v.target.value);setImageFiles(undefined);}}/></Field><div className="wb-form-grid"><Field label="第几条起"><input className="aiq-input" aria-label="可变数据起始记录" type="number" value={firstDraft} disabled={running} onChange={v=>setFirst(v.target.value)}/></Field><Field label="到第几条"><input className="aiq-input" aria-label="可变数据结束记录" type="number" value={lastDraft} disabled={running} onChange={v=>setLast(v.target.value)}/></Field><Field label="每块列数"><input className="aiq-input" aria-label="可变数据列容量" type="number" min="1" max="10" value={columnsDraft} disabled={running} onChange={v=>setColumns(v.target.value)}/></Field><Field label="每块行数"><input className="aiq-input" aria-label="可变数据行容量" type="number" min="1" max="100" value={rowsDraft} disabled={running} onChange={v=>setRowsPerBlock(v.target.value)}/></Field><Field label="横向间距 mm"><input className="aiq-input" aria-label="可变数据横向间距" type="number" value={gapDraft} disabled={running} onChange={v=>setGap(v.target.value)}/></Field><Field label="纵向间距 mm"><input className="aiq-input" aria-label="可变数据纵向间距" type="number" value={verticalGapDraft} disabled={running} onChange={v=>setVerticalGap(v.target.value)}/></Field></div>
 <p title="每块容量为列数 × 行数，填满后向右开始下一块。负间距或不足以容纳画板外设计的间距会明确拒绝，避免重叠。">每块容量 {Number.isInteger(columns*rowsPerBlock)?columns*rowsPerBlock:'—'} 条 · 向右分块</p>
 <Field label="画板名称来源"><select className="aiq-select" value={nameColumn} disabled={running} onChange={v=>setNameColumn(v.target.value)}><option value="">原表行号</option>{table?.columns.map(c=><option key={c.id} value={c.id}>{c.label}</option>)}</select></Field>
 <p role="status">可生成 {plan.records.length} 条 · 待处理问题 {plan.errors.length} 条</p>{planError&&<p role="alert">{planError}</p>}{plan.errors.slice(0,20).map(r=><p className="aiq-error-text" key={r.row}>表格第 {r.row} 行：{r.reason}</p>)}
 <div className="wb-inline-actions"><Button title="先生成一条到新的预览文档，核对文字、图片与二维码；原始模板保持不变。" disabled={e.busy||running||loading||!plan.records.length||!!planError||!!plan.errors.length} onClick={()=>void generate(true)}>预览第一条</Button><Button variant="primary" disabled={e.busy||running||loading||!plan.records.length||!!planError||!!plan.errors.length} onClick={()=>void generate(false)}>生成 {plan.records.length} 个画板</Button></div>
 {running&&<p role="status">正在生成{progress?` · ${progress.completed}/${progress.total}`:''}</p>}{running&&job&&<Button disabled={cancelling} onClick={()=>{setCancelling(true);void workspace.cancelExport(job).catch(err=>{setError(String(err));setCancelling(false);});}}>{cancelling?'等待当前记录结束':'取消后续生成'}</Button>}
 {results.length>0&&<><p>{results.filter(r=>r.status==='completed').length} 条完成 · {results.filter(r=>r.status==='failed').length} 条失败</p>{results.filter(r=>r.status==='failed').map(r=><p className="aiq-error-text" key={r.row}>第 {r.row} 行：{r.reason}</p>)}<p title="点击侧栏“文件导出”，选择需要的画板进行输出。">已生成内容位于当前成品文档，原始模板保持不变。</p></>}
 <EditorFeedback message={e.message} error={error||e.error}/></Card></div>;
}
