import { useEffect, useState } from 'react';
import type { EditorAction } from '@aiq/contracts';
import type { EditorPort } from './editor.js';
import { useEditor, EditorFeedback } from './editor.js';
import { Button, Field } from './components.js';
export function PropertyEditor({workspace,compact=false,hideTypography=false}:{workspace:EditorPort;compact?:boolean;hideTypography?:boolean}) {
 const e=useEditor(workspace,'properties',{autoRefresh:true}),[font,setFont]=useState(''),[size,setSize]=useState(''),[fill,setFill]=useState(''),[stroke,setStroke]=useState(''),[weight,setWeight]=useState('');
 const items=e.state?.objects??[],text=items.some(o=>o.kind.startsWith('text-'));
 useEffect(()=>{setFont('');setSize('');setFill('');setStroke('');setWeight('');},[e.state?.selectionKey]);
 const mixed=(key:'font'|'fontSize'|'fill'|'stroke'|'strokeWidth')=>{const v=items[0]?.[key];return v!==null&&v!==undefined&&items.every(o=>o[key]===v)?String(v):'混合 / 未解析';};
 const apply=()=>{const a:Extract<EditorAction,{type:'properties'}>={type:'properties'};if(font)a.font=font;if(size)a.fontSize=Number(size);if(fill)a.fill=fill;if(stroke)a.stroke=stroke;if(weight)a.strokeWidth=Number(weight);void e.act(a).then(r=>{if(r){setFont('');setSize('');setFill('');setStroke('');setWeight('');}});};
 return <section className={compact?'wb-property-bar':'wb-property-form'} aria-label="对象属性"><div className="wb-property-heading"><span>{items.length?`${items.length} 个对象`:e.state?.textSelection?'请退出文字编辑后选择文字框':'未选择对象'}</span><Button disabled={e.busy} onClick={()=>void e.read()} title="重新读取当前选区">刷新</Button></div>{items.length>0&&<><div className="wb-property-fields">{text&&!hideTypography&&<><Field label="字体"><input className="aiq-input" aria-label="属性字体" value={font} placeholder={mixed('font')} title="输入字体 PostScript 名称或唯一字体家族名称；只改文字框" onChange={v=>setFont(v.target.value)}/></Field><Field label="字号 pt"><input className="aiq-input" aria-label="属性字号" value={size} placeholder={mixed('fontSize')} onChange={v=>setSize(v.target.value)}/></Field></>}<Field label="填色"><div className="wb-color-input"><button className="wb-native-color" aria-label="选择填色" title="Illustrator 原生选色器；选取新颜色后确认直接应用，取消或颜色未改变时保持原样" style={{background:/^#[0-9a-f]{6}$/i.test(mixed('fill'))?mixed('fill'):'#808080'}} disabled={e.busy} onClick={()=>void e.act({type:'pick-color',target:'fill'})}/><input className="aiq-input" aria-label="属性填色" value={fill} placeholder={mixed('fill')} title="#RRGGBB；none 为无填色。空白保持原色。" onChange={v=>setFill(v.target.value)}/></div></Field><Field label="描边"><div className="wb-color-input"><button className="wb-native-color" aria-label="选择描边色" title="Illustrator 原生选色器；选取新颜色后确认直接应用，取消或颜色未改变时保持原样" style={{background:/^#[0-9a-f]{6}$/i.test(mixed('stroke'))?mixed('stroke'):'#808080'}} disabled={e.busy} onClick={()=>void e.act({type:'pick-color',target:'stroke'})}/><input className="aiq-input" aria-label="属性描边" value={stroke} placeholder={mixed('stroke')} title="#RRGGBB；none 为无描边" onChange={v=>setStroke(v.target.value)}/></div></Field><Field label="线宽 pt"><input className="aiq-input" aria-label="属性线宽" value={weight} placeholder={mixed('strokeWidth')} onChange={v=>setWeight(v.target.value)}/></Field><Button variant="primary" title="只修改填入的属性。文字按选中文字框处理，未填写的字体、字号及其他样式保持各自原值。" disabled={e.busy||!(font||size||fill||stroke||weight)} onClick={apply}>应用</Button></div></>}<EditorFeedback message={e.message} error={e.error}/></section>;
}
