import {usePreference} from '@aiq/ui';
import type { Workspace } from '@aiq/core';
import type { EditorAction } from '@aiq/contracts';
import { Button, Card, Field, useEditor, EditorFeedback, Segments } from '@aiq/ui';
import { TextSearch } from './TextSearch.js';
export function EditorReplacePanel({workspace}:{workspace:Workspace}) {
 const e=useEditor(workspace,'selection',{autoRefresh:true}),[remove,setRemove]=usePreference(workspace,'replace.remove',true),[mode,setMode]=usePreference<NonNullable<Extract<EditorAction,{type:'replace'}>['scaleMode']>>(workspace,'replace.mode','original'),[tab,setTab]=usePreference<'objects'|'text'>(workspace,'replace.tab','objects');
 return <><Segments label="替换类型" value={tab} onChange={setTab} options={[["objects","图形替换"],["text","查找文字"]]}/>{tab==='text'?<TextSearch workspace={workspace}/>:<Card title="将目标 A 替换成来源 B" icon="select"><div className="wb-step"><b>1</b><div className="wb-replace-source"><strong>选择作为模型的来源 B</strong><div className="wb-replace-source-actions"><Button title="可选一个图形、群组或复合路径作为来源 B。" disabled={e.busy} onClick={()=>void e.act({type:'capture-targets',role:'source'})}>记住来源 B</Button><Button title="清除记住的来源" aria-label="清除来源" disabled={e.busy||!e.state?.capturedSource} onClick={()=>void e.act({type:'capture-targets',role:'clear'})}>×</Button></div><span className="wb-inline-note">{e.state?.capturedSource?'已记住来源 B':'尚未记住来源'}</span></div></div><div className="wb-step"><b>2</b><div><strong>在画布选择要替换的目标 A</strong></div></div><Field label="替换尺寸"><select className="aiq-select" aria-label="替换尺寸" value={mode} disabled={e.busy} onChange={v=>setMode(v.target.value as typeof mode)}>{([['original','保持 B 原尺寸'],['stretch','缩放到 A 宽高'],['height','按 A 高度等比缩放'],['width','按 A 宽度等比缩放']] as const).map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></Field><label className="wb-check"><input type="checkbox" checked={remove} onChange={v=>setRemove(v.target.checked)}/>替换后移除原 A</label><Button variant="primary" title="支持框选多个目标，保留各自位置与层级。" disabled={e.busy||!e.state?.capturedSource} onClick={()=>void e.act({type:'replace',removeTargets:remove,fit:false,scaleMode:mode,sourceFirst:true})}>替换所选目标</Button><EditorFeedback message={e.message} error={e.error}/></Card>}</>;
}
