import { largeRasterNeeded, rasterDimensions } from './raster-routing.js';
import { ScaleField, scalePercent } from './ScaleField.js';
import { useEffect, useState } from 'react';
import type { Workspace } from '@aiq/core';
import { parseArtboardRange, unitFactor } from '@aiq/core';
import type { EditorAction, EditorState, ExportProgress } from '@aiq/contracts';
import { PresetInput, Chevron, boardTargets, resolveBoardTargets, AnnotationColor, ArtboardPicker, Button, Card, Field, Segments, useEditor, EditorFeedback } from '@aiq/ui';
import { DEFAULT_NAMING, ExportNamingFields } from './ExportNamingFields.js';
import { ExportDirectory } from './ExportDirectory.js';
import { ExportJobStatus } from './ExportJobStatus.js';
import { useExportSetting } from './use-export-setting.js';
type Format=Extract<EditorAction,{type:'export'}>['format'];
const FORMATS:Array<[Format,string]>=[["png","PNG"],["jpeg","JPEG"],["svg","SVG"],["pdf","PDF"],["ai","AI"],["eps","EPS"],["tif","TIF"],["psd","PSD"]];
export function EditorExportPanel({workspace}:{workspace:Workspace}) {
 // Historical jobs remain on disk for diagnosis; a new panel/document never inherits their failure state.
 const [jobId,setJobId]=useState(''),[running,setRunning]=useState(false),[progress,setProgress]=useState<ExportProgress|null>(null);
 const [naming,setNaming]=useState(workspace.getSettings().exportNaming??DEFAULT_NAMING),[scale,setScale]=useState(String((workspace.getSettings().exportScale??100)/100)),[lastFolder,setLastFolder]=useState('');
 const [screenExport,setScreenExport]=useExportSetting(workspace,'screenExport',false);
 const [rasterIndependent,setRasterIndependent]=useExportSetting(workspace,'rasterIndependent',false),[rasterProfile,setRasterProfile]=useExportSetting(workspace,'rasterProfile','source'),[rasterIccPath,setRasterIccPath]=useExportSetting(workspace,'rasterIccPath',''),[rasterOptimize,setRasterOptimize]=useExportSetting(workspace,'rasterOptimize',true);
 const [rasterConvertSpots,setRasterConvertSpots]=useExportSetting(workspace,'rasterConvertSpots',false),[rasterSmoothing,setRasterSmoothing]=useExportSetting(workspace,'rasterSmoothing','high'),[writeLayers,setWriteLayers]=useExportSetting(workspace,'writeLayers',true),[layeredTiff,setLayeredTiff]=useExportSetting(workspace,'layeredTiff',false);
 const [pdfCompatible,setPdfCompatible]=useExportSetting(workspace,'pdfCompatible',true);
 const [compression,setCompression]=useExportSetting(workspace,'compression',true),[outlineText,setOutlineText]=useExportSetting(workspace,'outlineText',false),[overprintBlack,setOverprintBlack]=useExportSetting(workspace,'overprintBlack',false);
 const [boardOpen,setBoardOpen]=useState(false),[openFolder,setOpenFolder]=useState(workspace.getSettings().exportOpenFolder??false);
 useEffect(()=>{if(!boardOpen)return;const close=(e:KeyboardEvent)=>{if(e.key==='Escape')setBoardOpen(false);};window.addEventListener('keydown',close);return()=>window.removeEventListener('keydown',close);},[boardOpen]);
 const [format,setFormat]=useExportSetting(workspace,'format','png'),[target,setTarget]=useExportSetting(workspace,'target','objects');
 const e=useEditor(workspace,target==='artboards'?'document':'selection',{autoRefresh:true});
 const [folder,setFolder]=useState(workspace.getSettings().exportFolder??''),[alongside,setAlongside]=useState(workspace.getSettings().exportAlongsideSource??false);
 const [createSubfolder,setCreateSubfolder]=useState(workspace.getSettings().exportCreateSubfolder??false),[subfolderName,setSubfolderName]=useState(workspace.getSettings().exportSubfolderName??'导出');

 const [bleedMode,setBleedMode]=useExportSetting(workspace,'bleedMode','manual');const nativeBleed=workspace.getDocumentBleed?.()??null;
 const [colorMode,setColorMode]=useExportSetting(workspace,'colorMode','source');
 const [dpi,setDpi]=useExportSetting(workspace,'dpi','300'),[quality,setQuality]=useExportSetting(workspace,'quality','100'),[transparent,setTransparent]=useExportSetting(workspace,'transparent',true),[editable,setEditable]=useExportSetting(workspace,'editable',false),[embed,setEmbed]=useExportSetting(workspace,'embed',false);
 const [manualBoards,setManualBoards]=useState<{doc:string;indexes:number[]}|null>(null),[range,setRange]=useState(''),[name,setName]=useState(''),[useBleed,setUseBleed]=useExportSetting(workspace,'useBleed',false),[bleed,setBleed]=useExportSetting(workspace,'bleed','3'),[offset,setOffset]=useExportSetting(workspace,'offset','3'),[error,setError]=useState('');
 // Follow each shared state update until the user explicitly overrides the range.
 const following=!manualBoards||manualBoards.doc!==e.state?.docSessionId;
 const selected=following?(e.state&&!e.state.artboardSelectionError?boardTargets(e.state.artboards,e.state.activeArtboard,'active',[],e.state.selectedArtboards):[]):(manualBoards?.indexes??[]);
 const setSelected=(indexes:number[])=>setManualBoards({doc:e.state?.docSessionId??'',indexes});
 const [annotation,setAnnotation]=useExportSetting(workspace,'annotation',{enabled:false,size:true,resolution:false,colors:false,bleed:false,position:'bottom-left',offset:0});
 useEffect(()=>{setManualBoards(null);setRange('');setName('');setLastFolder('');setJobId('');setProgress(null);setError('');},[e.state?.docSessionId]);
 const remember=(value:string)=>{setFolder(value);setAlongside(false);workspace.updateSettings({exportFolder:value,exportAlongsideSource:false});};
 const currentFolder=alongside?(e.state?.sourceFolder??''):folder.trim();
 const screenMode=screenExport&&target==='artboards'&&['jpeg','png'].includes(format);
 const independentAllowed=target==='artboards'&&['png','jpeg','tif'].includes(format)&&!(format==='tif'&&layeredTiff);
 const autoRaster=(state:EditorState|null)=>{if(!state||!independentAllowed)return false;const indexes=following?boardTargets(state.artboards,state.activeArtboard,'active',[],state.selectedArtboards):selected;const sides=!useBleed||screenMode?[0,0,0,0]:bleedMode==='document'?(state.bleedOffsets??[]):Array(4).fill(Number(bleed)*(state.rulerUnit?unitFactor(state.rulerUnit):NaN));return largeRasterNeeded(state.artboards.filter(b=>indexes.includes(b.index)).map(b=>b.bounds),Number(scale)*100,Number(dpi),sides);};
 const autoIndependent=autoRaster(e.state);
 const independent=independentAllowed&&((!screenMode&&rasterIndependent)||autoIndependent);
 const sides=!useBleed||screenMode?[0,0,0,0]:bleedMode==='document'?(e.state?.bleedOffsets??[]):Array(4).fill(Number(bleed)*(e.state?.rulerUnit?unitFactor(e.state.rulerUnit):NaN));
 const pixelSizes=target==='artboards'&&['png','jpeg','tif','psd'].includes(format)?rasterDimensions(e.state?.artboards.filter(b=>selected.includes(b.index)).map(b=>b.bounds)??[],Number(scale)*100,Number(dpi),sides):[];
 const pixelSummary=pixelSizes.length===1?`${pixelSizes[0]![0]} × ${pixelSizes[0]![1]} px`:pixelSizes.length?`${pixelSizes.length} 画板 · 最大 ${Math.max(...pixelSizes.map(v=>v[0]))} × ${Math.max(...pixelSizes.map(v=>v[1]))} px`:'';
 const rgbOnly=screenMode||['png','svg'].includes(format);
 const outputColor=rgbOnly?'rgb':colorMode;
 const actualColor=outputColor==='source'?e.state?.colorSpace:outputColor;
 const canOverprint=['pdf','ai','eps'].includes(format)&&actualColor==='cmyk',canOutline=['pdf','ai','eps','svg'].includes(format);
 const changeNaming=(value:typeof naming)=>{setNaming(value);workspace.updateSettings({exportNaming:value});};
 const unit=e.state?.rulerUnit;
 const applyRange=()=>{try{setSelected(parseArtboardRange(range,e.state?.artboards.length??0));setError('');}catch(err){setError(String(err));}};
 const submit=()=>{setError('');try{if(!dpi.trim()||!Number.isFinite(Number(dpi))||Number(dpi)<1||Number(dpi)>2400)throw Error('分辨率须为 1–2400 ppi');const percent=scalePercent(scale);if(annotation.enabled&&annotation.color&&!/^#[\da-f]{6}$/i.test(annotation.color))throw Error('标注颜色须为 #RRGGBB');workspace.updateSettings({exportScale:percent});const bleedPoints=(target==='artboards'?Number(bleed):0)*unitFactor(unit);const annotationInset=Number(offset)*unitFactor(unit);if(!Number.isFinite(bleedPoints)||bleedPoints<0||bleedPoints>720){throw Error('出血须为非负数且不超过 720 pt');}if(!Number.isFinite(annotationInset)||annotationInset<0){throw Error('标注偏移须为非负数');}const id=workspace.supportsExportProgress?.()?('job-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2,10)):undefined;if(id){setJobId(id);setRunning(true);setProgress(null);workspace.updateSettings({lastExportJobId:id});}let usedIndependent=independent;void e.act(state=>{usedIndependent=independentAllowed&&((!screenMode&&rasterIndependent)||autoRaster(state));return {type:'export',rasterEngine:usedIndependent?'independent':undefined,rasterSmoothing:usedIndependent?rasterSmoothing:undefined,rasterConvertSpots:usedIndependent&&rasterConvertSpots,writeLayers:format==='psd'?writeLayers:format==='tif'?layeredTiff:undefined,rasterProfile,rasterIccPath:rasterIccPath.trim(),rasterOptimize,screenExport:screenMode,jobId:id,naming,pdfCompatible:format==='ai'?pdfCompatible:undefined,compression:['ai','pdf'].includes(format)?compression:undefined,antiAliasing:true,outlineText:canOutline&&outlineText,overprintBlack:canOverprint&&overprintBlack,openFolderAfterExport:openFolder,colorMode:outputColor,createSubfolder,subfolderName:subfolderName.trim(),target,format,artboardIndexes:target==='artboards'?(following?resolveBoardTargets(state,'active'):resolveBoardTargets(state,'custom',selected)):undefined,allArtboards:false,scale:percent,resolution:Number(dpi),quality:Number(quality),folder:folder.trim(),sourceFolder:alongside,transparent,preserveEditability:editable,embedImages:embed,fileName:name.trim(),namingMode:'name',bleedPoints,bleedMode,useDocumentBleed:target==='artboards'&&useBleed&&!screenMode,annotation:{...annotation,enabled:target==='artboards'&&format==='pdf'&&annotation.enabled,offset:annotationInset}};}).then(result=>{if(result?.exportProgress)setProgress(result.exportProgress);if(usedIndependent&&openFolder&&result?.files?.length&&result.folder)void e.act({type:'open-folder',folder:result.folder});if(result?.files?.length&&result.folder)setLastFolder(result.folder);if(result?.files?.length&&currentFolder){const history=workspace.getSettings().exportFolders??[];workspace.updateSettings({exportFolders:[currentFolder,...history.filter(path=>path!==currentFolder)].slice(0,8)});}}).finally(()=>setRunning(false));}catch(err){setError(err instanceof Error?err.message:String(err));}};
 return <div className="wb-export-panel"><div className="wb-export-scroll"><div className="wb-export-target"><Segments label="导出范围" value={target} onChange={next=>{setTarget(next);setError('');}} options={[["objects","所选对象"],["artboards","指定画板"]]}/>{target==='artboards'?<div className="wb-input-reset wb-export-board-controls"><Button disabled={e.busy} title="把画板工具当前多选（或活动画板）同步为导出范围" aria-pressed={following} onClick={()=>setManualBoards(null)}>跟随画板选择</Button><Button disabled={e.busy} onClick={()=>setBoardOpen(true)}>选择画板 · {selected.length} <Chevron/></Button></div>:<span className="wb-inline-note">已选 {e.state?.objects.length??0} 项</span>}</div>
 {target==='artboards'&&following&&e.state?.artboardSelectionError&&<p className="aiq-error-text" role="alert">{e.state.artboardSelectionError}</p>}
 {boardOpen&&<div className="wb-modal-mask" role="dialog" aria-label="选择导出画板" onClick={v=>{if(v.target===v.currentTarget)setBoardOpen(false);}}><div className="wb-modal"><h3>画板与页序 · 已选 {selected.length}</h3><ArtboardPicker boards={e.state?.artboards??[]} selected={selected} onChange={setSelected} disabled={e.busy} tools={<><input className="aiq-input wb-range-input" aria-label="画板范围" placeholder="1,3,5-8" value={range} onChange={v=>setRange(v.target.value)}/><Button disabled={e.busy} onClick={applyRange}>选择范围</Button></>}/><EditorFeedback message="" error={error}/><Button onClick={()=>setBoardOpen(false)}>完成选择</Button></div></div>}
 <Card title="输出" icon="doc">
 <ExportDirectory workspace={workspace} folder={folder} currentFolder={currentFolder} alongside={alongside} busy={e.busy} onOpen={()=>void e.act({type:'open-folder',folder:lastFolder||currentFolder})} onChange={value=>{setLastFolder('');remember(value);}} onChoose={()=>void e.act({type:'choose-folder'}).then(r=>{if(r?.folder){setLastFolder('');remember(r.folder);if(r.fileName)setName(r.fileName);}})}/>
 <div className="wb-directory-options"><label className="wb-check"><input type="checkbox" checked={alongside} disabled={e.busy} onChange={v=>{setLastFolder('');setAlongside(v.target.checked);workspace.updateSettings({exportAlongsideSource:v.target.checked});}}/>跟随源文件目录</label>
 <label className="wb-check"><input type="checkbox" checked={createSubfolder} disabled={e.busy} onChange={v=>{setCreateSubfolder(v.target.checked);workspace.updateSettings({exportCreateSubfolder:v.target.checked});}}/>建立子目录</label></div>
 {createSubfolder&&<Field label="子目录名称"><input className="aiq-input" aria-label="子目录名称" value={subfolderName} disabled={e.busy} onChange={v=>{setSubfolderName(v.target.value);workspace.updateSettings({exportSubfolderName:v.target.value});}}/></Field>}

 <div className="wb-export-name"><Field label="文件名"><input className="aiq-input" aria-label="导出文件名" value={name} onChange={v=>setName(v.target.value)} placeholder="留空使用文档名-画板名"/></Field></div>
 <ExportNamingFields value={naming} onChange={changeNaming}/>
 <ScaleField help={(canOutline?"成品缩放改变矢量物理尺寸；ppi 仅影响栅格效果，PDF 还用于图像降采样。SVG 固定 RGB。":"成品缩放与 ppi 共同决定像素尺寸；出血随倍率缩放。已有位图的细节取决于原图。")+(format==='psd'?" PSD 尽量保留图层与文字，复杂外观可能合并或栅格化。":"")} value={scale} onChange={value=>{setScale(value);try{workspace.updateSettings({exportScale:scalePercent(value)});}catch{/* Keep incomplete drafts locally. */}}}/>
 
 {format==='psd'&&<><label className="wb-check" title="由 Illustrator 原生写入；复杂外观可能合并。需要图层时保持源颜色模式。"><input type="checkbox" aria-label="保留 PSD 图层" checked={writeLayers} onChange={v=>setWriteLayers(v.target.checked)}/>保留 PSD 图层</label></>}{format==='tif'&&<><label className="wb-check" title={layeredTiff?'通过分层 PSD 在 Photoshop 保存为 TIF；LZW／ZIP 无损压缩，复杂外观可能合并。':'当前 TIF 输出为合并图像，使用 LZW 无损压缩。原生路径需要 Photoshop 保留 ICC；独立渲染无需 Photoshop。'}><input type="checkbox" aria-label="保留 TIF 图层（需要 Photoshop）" checked={layeredTiff} onChange={v=>setLayeredTiff(v.target.checked)}/>保留 TIF 图层（需要 Photoshop）</label></>}{format==='png'&&<label className="wb-check" title="PNG 为 RGB 无损格式；勾选后保留透明背景。"><input type="checkbox" checked={transparent} onChange={v=>setTransparent(v.target.checked)}/>透明背景</label>}
 {target==='artboards'&&<div className="wb-bleed-settings"><label className="wb-check"><input type="checkbox" checked={useBleed} onChange={v=>setUseBleed(v.target.checked)}/>使用出血</label>{useBleed&&<><div className="wb-bleed-row"><Segments label="出血来源" value={bleedMode} onChange={setBleedMode} options={[["manual","手动出血"],["document","文档出血"]]}/></div>{bleedMode==='manual'?<Field label={`出血量（四边） ${unit??''}`}><input className="aiq-input wb-num-input" aria-label="出血量" value={bleed} onChange={v=>setBleed(v.target.value)}/></Field>:nativeBleed&&<p className="wb-inline-note">{nativeBleed.map((v,i)=>['左','上','右','下'][i]+' '+Number((v/unitFactor(unit)).toFixed(3))+' '+unit).join(' · ')}</p>}</>}</div>}
 <label className="wb-check"><input type="checkbox" aria-label="导出后打开文件夹" checked={openFolder} onChange={v=>{setOpenFolder(v.target.checked);workspace.updateSettings({exportOpenFolder:v.target.checked});}}/>导出后自动打开文件夹</label>
 {target==='artboards'&&['png','jpeg'].includes(format)&&<><label className="wb-check" title="开启时设为 72 PPI，可自行修改。沿用原稿效果，不含出血；JPEG 品质可自行设置。批次之间可取消。"><input type="checkbox" aria-label="屏幕导出" checked={screenMode} onChange={v=>{setScreenExport(v.target.checked);if(v.target.checked){setDpi('72');setUseBleed(false);}}}/>屏幕导出（RGB）</label></>}
 {target==='artboards'&&['jpeg','png','tif'].includes(format)&&!screenMode&&!(format==='tif'&&layeredTiff)&&<><Field label="渲染器" help="自动模式下，小图使用 Illustrator 原生渲染并开启边缘平滑，超过原生像素限制时使用独立渲染；始终独立会对受支持的位图固定使用独立引擎。保持倍率、PPI 和颜色设置，仍受内存与暂存空间限制。独立准备过程会使用受保护工作副本。"><select className="aiq-select" aria-label="渲染器" value={rasterIndependent?'independent':'auto'} onChange={v=>setRasterIndependent(v.target.value==='independent')}><option value="auto">自动选择渲染器（小图原生，大图独立）</option><option value="independent">始终独立渲染</option></select></Field>{autoIndependent&&<p className="wb-inline-note">当前尺寸将自动使用独立渲染。</p>}{independent&&<><Field label="边缘平滑" help="仅改善边缘，成品尺寸、倍率和 PPI 不变；精细模式更慢且需要更多暂存空间。"><select className="aiq-select" aria-label="边缘平滑" value={rasterSmoothing} onChange={v=>setRasterSmoothing(v.target.value as typeof rasterSmoothing)}><option value="standard">标准 · 2 倍采样</option><option value="high">精细 · 4 倍采样</option></select></Field><label className="wb-check" title="仅位图按专色预览颜色转为 RGB／CMYK，不保留独立油墨通道；原 AI／PDF 不变。"><input type="checkbox" aria-label="专色转为画面近似色" checked={rasterConvertSpots} onChange={v=>setRasterConvertSpots(v.target.checked)}/>专色转为画面近似色</label><Field label="输出 ICC 配置" help="沿用 ICC 不等于不同引擎逐像素一致；标准／厂家 ICC 会进行颜色转换。"><select className="aiq-select" value={rasterProfile} onChange={v=>setRasterProfile(v.target.value as typeof rasterProfile)}><option value="source">沿用稿件配置（无法确认时提示）</option><option value="standard">{actualColor==='cmyk'?'标准 CMYK（Artifex SWOP）':'标准 RGB（sRGB）'}</option><option value="custom">使用厂家 ICC 文件</option></select></Field>{rasterProfile==='custom'&&<Field label="ICC 文件完整路径"><input className="aiq-input" value={rasterIccPath} onChange={v=>setRasterIccPath(v.target.value)} placeholder="粘贴 .icc 或 .icm 文件路径"/></Field>}{format==='jpeg'&&<label className="wb-check"><input type="checkbox" checked={rasterOptimize} onChange={v=>setRasterOptimize(v.target.checked)}/>JPG 无损优化体积（不降低品质）</label>}</>}</>}
 
 <section className="wb-export-options" aria-label="更多设置">
 <div className="wb-export-toggles">{['ai','pdf'].includes(format)&&<label className="wb-check"><input type="checkbox" aria-label="无损压缩" checked={compression} onChange={v=>setCompression(v.target.checked)}/>无损压缩</label>}{canOutline&&<label className="wb-check"><input type="checkbox" aria-label="导出副本文字转曲" checked={outlineText} onChange={v=>setOutlineText(v.target.checked)}/>可见文字转曲</label>}{canOverprint&&<label className="wb-check" title="仅将普通路径和文字中的 C0 M0 Y0 K100 填充、描边设为叠印；不改变其他颜色"><input type="checkbox" aria-label="纯黑叠印" checked={overprintBlack} onChange={v=>setOverprintBlack(v.target.checked)}/>纯黑叠印</label>}</div>
 {format==='jpeg'&&<Field label="JPEG 品质 0–100" help="JPEG 即使品质 100 也不是像素无损；需要完全无损请选择 TIF 或 PNG。"><input className="aiq-input" value={quality} onChange={v=>setQuality(v.target.value)}/></Field>}
 {format==='ai'&&<><label className="wb-check" title="关闭通常可减少保存时间和体积，仍可在 Illustrator 编辑；需要其他软件读取或置入时开启。"><input type="checkbox" aria-label="创建 PDF 兼容文件" checked={pdfCompatible} onChange={v=>setPdfCompatible(v.target.checked)}/>创建 PDF 兼容文件</label></>}{format==='pdf'&&<label className="wb-check"><input type="checkbox" checked={editable} onChange={v=>setEditable(v.target.checked)}/>保留 Illustrator 编辑能力</label>}
 {(format==='ai'||format==='eps')&&<label className="wb-check"><input type="checkbox" checked={embed} onChange={v=>setEmbed(v.target.checked)}/>嵌入链接图片</label>}
 {target==='artboards'&&format==='pdf'&&<Field label={`出血要求标注 ${unit??''}`}><input className="aiq-input wb-num-input" aria-label="出血" title="仅在 PDF 副本上标注出血要求文字，不生成出血框" value={bleed} onChange={v=>setBleed(v.target.value)}/></Field>}</section></Card>
 {target==='artboards'&&format==='pdf'&&<details className="wb-details"><summary>PDF 规格标注</summary><label className="wb-check"><input type="checkbox" checked={annotation.enabled} onChange={v=>setAnnotation({...annotation,enabled:v.target.checked})}/>添加到 PDF 副本</label>{annotation.enabled&&<><AnnotationColor value={annotation.color??'#2364c8'} onChange={color=>setAnnotation({...annotation,color})}/><div className="wb-scope-options">{(['size','resolution','colors','bleed'] as const).map(k=><label key={k}><input type="checkbox" checked={annotation[k]} onChange={v=>setAnnotation({...annotation,[k]:v.target.checked})}/>{({size:'尺寸',resolution:'导出 ppi',colors:'使用色值',bleed:'出血要求'})[k]}</label>)}</div><Segments label="标注位置" value={annotation.position} onChange={v=>setAnnotation({...annotation,position:v})} options={[["top-left","左上"],["top-right","右上"],["bottom-left","左下"],["bottom-right","右下"]]}/><Field label={`距边 ${unit??''}`}><input className="aiq-input wb-num-input" aria-label="标注偏移" value={offset} onChange={v=>setOffset(v.target.value)}/></Field></>}</details>}
 </div><div className="wb-export-actions">{pixelSummary&&<div className="wb-output-summary" role="status" title="按所选画板、出血、成品倍率与 PPI 计算；多画板显示宽高各自最大值。不会自动降低分辨率。">{pixelSummary} · {independent?'独立渲染':'原生渲染'}</div>}<Segments label="导出格式" value={format} onChange={setFormat} options={FORMATS}/><div className="wb-export-command"> <Field label="导出颜色模式" help={independent?"沿用源配置或按指定 ICC 转换颜色。":"Illustrator 原生渲染并开启边缘平滑；PNG 固定 RGB，JPEG 支持 RGB／CMYK，颜色模式不代表像素无损。"}><select className="aiq-select" aria-label="导出颜色模式" value={outputColor} disabled={rgbOnly||e.busy} onChange={v=>setColorMode(v.target.value as typeof colorMode)}><option value="source">跟随源文件{e.state?.colorSpace?' · '+e.state.colorSpace.toUpperCase():''}</option><option value="rgb">RGB</option><option value="cmyk">CMYK</option></select></Field>{format!=='svg'&&<Field label="PPI"><PresetInput label="导出分辨率" inputMode="decimal" value={dpi} onChange={setDpi} presets={[50,72,100,150,200,300,400,600]} disabled={e.busy}/></Field>}<Button variant="primary" disabled={e.busy||!e.state||!unit||!currentFolder||(createSubfolder&&!subfolderName.trim())||(target==='objects'?!e.state.objects.length:!selected.length)} onClick={submit}>{target==='objects'?`导出所选`:`导出 ${selected.length} 画板`}</Button></div><ExportJobStatus workspace={workspace} jobId={jobId} running={running} result={progress}/><EditorFeedback message={e.message} error={error||e.error}/></div></div>;
}
