import {useEffect,useState} from 'react';
import type {Workspace} from '@aiq/core';
import {numberSequence,unitFactor} from '@aiq/core';
import type {ProductivityAction,ProductivityRow,ToolContribution} from '@aiq/contracts';
import {Button,Card,Field,ArtboardPicker,useEditor,usePreference,EditorFeedback} from '@aiq/ui';
import {barcodePlan} from './barcode.js';
import {lengthOptions} from './length-options.js';
type Operation=ProductivityAction['operation'];
type ActionPayload=ProductivityAction extends infer A?A extends ProductivityAction?Omit<A,'type'>:never:never;
const tools:Array<[Operation,string]>=[['mask-fit','蒙版内图片调整'],['duplicate-boards','多画板同位置复制'],['text-fit','文字溢出与适配'],['text-merge','碎文字合并'],['baseline','文字基线对齐'],['sequence','流水号与页码'],['barcode','条码联动流水号'],['photoshop','一键 Photoshop']];
const defaults={valueUnit:'',start:'1',step:'1',count:'1',digits:'3',prefix:'',suffix:'',order:'rows' as 'rows'|'columns',placeholder:'{%N}',target:'text' as 'text'|'pages'|'board-names',x:'5',y:'5',fontSize:'12',minSize:'8',maxHeight:'300',tolerance:'2',separator:'',removeOriginals:false,anchor:'4',dx:'0',dy:'0',barcodeFormat:'code128' as 'code128'|'ean13',moduleWidth:'0.33',barHeight:'20',barcodeInput:'sequence' as 'sequence'|'lines'};
export function ProductivityPanel({workspace,tool}:{workspace:Workspace;tool?:ToolContribution}){
 const e=useEditor(workspace,'selection',{autoRefresh:true});
 const [op,setOp]=usePreference<Operation>(workspace,'productivity.operation','mask-fit'),[p,setP]=usePreference(workspace,'productivity.options',defaults);
 const unit=e.state?.rulerUnit,factor=unit?unitFactor(unit):NaN;
 const options=lengthOptions({...defaults,...p},unit);
 const [indexes,setIndexes]=useState<number[]>([]),[rows,setRows]=useState<ProductivityRow[]>([]),[error,setError]=useState(''),[lines,setLines]=useState('');
 useEffect(()=>{if(tool&&tools.some(([id])=>id===tool.id))setOp(tool.id as Operation);},[tool?.id]); // eslint-disable-line react-hooks/exhaustive-deps
 useEffect(()=>{setIndexes([]);setRows([]);setError('');},[e.state?.docSessionId]);
 const set=<K extends keyof typeof defaults>(key:K,value:(typeof defaults)[K])=>setP({...options,valueUnit:unit??options.valueUnit,[key]:value});
 const field=(key:keyof typeof defaults,label:string)=><Field label={label}><input className="aiq-input" aria-label={label} value={String(options[key])} onChange={v=>set(key,v.target.value as never)} onBlur={v=>{if(['x','y','maxHeight','tolerance','dx','dy'].includes(key)&&v.target.value.trim()&&Number.isFinite(Number(v.target.value)))set(key,String(Number(Number(v.target.value).toFixed(2))) as never);}}/></Field>;
 const num=(key:keyof typeof defaults)=>{const raw=String(options[key]);if(!raw.trim()||!Number.isFinite(Number(raw)))throw Error('请填写有效数值');return Number(raw);};
 const length=(key:keyof typeof defaults)=>{if(!Number.isFinite(factor))throw Error('文档单位不可用，请重新读取');return num(key)*factor;};
 const values=()=>numberSequence({start:num('start'),step:num('step'),count:num('count'),digits:num('digits'),prefix:options.prefix,suffix:options.suffix});
 let preview='';try{preview=values().slice(0,6).join('、');}catch{/* Show validation on explicit action. */}
 const run=async(build:()=>ActionPayload)=>{setError('');setRows([]);try{const action={type:'productivity',...build()} as ProductivityAction;const result=await e.act(fresh=>{
  if(fresh.rulerUnit!==unit)throw Error('文档单位已改变，请读取后核对参数再执行');
  if((action.operation==='duplicate-boards'||action.operation==='sequence'&&action.target!=='text')&&JSON.stringify(fresh.artboards)!==JSON.stringify(e.state?.artboards))throw Error('画板已改变，请重新读取并勾选');
  return action;
 });if(result?.productivityRows)setRows(result.productivityRows);}catch(err){setError(err instanceof Error?err.message:'参数无效');}};
 const boards=<ArtboardPicker boards={e.state?.artboards??[]} selected={indexes} onChange={setIndexes} disabled={e.busy}/>;
 const sequenceFields=<><div className="wb-text-fields">{field('start','起始值')}{field('step','步长')}{field('count','数量')}{field('digits','补零位数')}{field('prefix','前缀')}{field('suffix','后缀')}</div><p className="wb-inline-note">编号预览：{preview||'请检查参数'}</p></>;
 const order=<Field label="对象顺序"><select className="aiq-select" value={options.order} onChange={v=>set('order',v.target.value as typeof options.order)}><option value="rows">从上到下，同行从左到右</option><option value="columns">从左到右，同列从上到下</option></select></Field>;
 return <>{!tool&&<Field label="生产辅助功能"><select className="aiq-select" value={op} onChange={v=>{setOp(v.target.value as Operation);setRows([]);setError('');}}>{tools.map(([id,title])=><option key={id} value={id}>{title}</option>)}</select></Field>}<Button disabled={e.busy} onClick={()=>void e.read()}>读取选区与画板</Button>
 <Card title={tools.find(([id])=>id===op)?.[1]??'生产辅助'} icon="modules">
 {op==='mask-fit'&&<><p>选中剪切蒙版群组：内部须为一张图片或一个完整内容群组。按蒙版外框适配。</p><Field label="图片定位"><select className="aiq-select" value={options.anchor} onChange={v=>set('anchor',v.target.value)}>{['左上','上中','右上','左中','居中','右中','左下','下中','右下'].map((name,i)=><option key={i} value={i}>{name}</option>)}</select></Field><div className="wb-text-fields">{field('dx',`水平偏移 ${unit??'—'}`)}{field('dy',`向下偏移 ${unit??'—'}`)}</div><div className="aiq-row">{(['cover','contain','width','height','stretch','position'] as const).map((mode,i)=><Button key={mode} disabled={e.busy} onClick={()=>void run(()=>({operation:'mask-fit',mode,anchorX:(num('anchor')%3)/2,anchorY:Math.floor(num('anchor')/3)/2,dx:length('dx'),dy:length('dy')}))}>{['填满蒙版','适合蒙版','横向等比','纵向等比','自由缩放填充','仅定位'][i]}</Button>)}</div></>}
 {op==='duplicate-boards'&&<><p>以当前活动画板左上角为参照，复制所选顶层对象／完整群组。跳过来源画板，保持图层。</p>{boards}<Button disabled={e.busy||!indexes.length} onClick={()=>void run(()=>({operation:'duplicate-boards',indexes}))}>复制到勾选画板</Button></>}
 {op==='text-fit'&&<><p>只读检查所选独立区域文字，每批最多 50 框。</p><p className="wb-inline-note">缩字／文字比例适配等待原生内存排版预检：目前不试改原稿，不创建临时文档。尚不能计算可容纳字号。</p><Button disabled={e.busy} onClick={()=>void run(()=>({operation:'text-fit',mode:'inspect',minSize:num('minSize'),maxHeight:length('maxHeight')}))}>只检查溢出</Button></>}
 {op==='text-merge'&&<><p>同图层的单行、水平点文字，按行重组并保留字符样式。不能恢复转曲文字或执行 OCR。</p><div className="wb-text-fields">{field('tolerance',`同行容差 ${unit??'—'}`)}{field('separator','同一行片段分隔符')}</div><label className="wb-check"><input type="checkbox" checked={options.removeOriginals} onChange={v=>set('removeOriginals',v.target.checked)}/>合并后替换原文字（未勾选时在下方生成新框）</label><Button disabled={e.busy} onClick={()=>void run(()=>({operation:'text-merge',tolerance:length('tolerance'),separator:options.separator,removeOriginals:options.removeOriginals}))}>合并所选碎文字</Button></>}
 {op==='baseline'&&<><p>选中至少两个未旋转的单行点文字，统一到最低文字基线；字号与字符自身偏移保持不变。</p><Button disabled={e.busy} onClick={()=>void run(()=>({operation:'baseline'}))}>对齐文字基线</Button></>}
 {op==='sequence'&&<><Field label="编号用途"><select className="aiq-select" value={options.target} onChange={v=>set('target',v.target.value as typeof options.target)}><option value="text">替换所选文字中的占位符</option><option value="pages">在指定画板添加页码</option><option value="board-names">编号命名指定画板</option></select></Field>{sequenceFields}{options.target==='text'?<>{field('placeholder','编号占位符')}{order}<p>每框须恰好包含一个占位符；数量须等于文字框数。同一行容差为 3 pt。</p></>:<>{boards}{options.target==='pages'&&<div className="wb-text-fields">{field('x',`距画板左侧 ${unit??'—'}`)}{field('y',`距画板顶部 ${unit??'—'}`)}{field('fontSize','页码字号 pt')}</div>}</>}<Button disabled={e.busy} onClick={()=>void run(()=>({operation:'sequence',values:values(),order:options.order,placeholder:options.placeholder,target:options.target,indexes,offsetX:length('x'),offsetY:length('y'),fontSize:num('fontSize')}))}>应用编号</Button></>}
 {op==='barcode'&&<><p>选中定位对象，每个对象下方生成一个条码，不删除原对象。静区固定留 12 个模块。</p><Field label="条码数据"><select className="aiq-select" value={options.barcodeInput} onChange={v=>set('barcodeInput',v.target.value as typeof options.barcodeInput)}><option value="sequence">使用流水号</option><option value="lines">每行一个内容</option></select></Field>{options.barcodeInput==='sequence'?sequenceFields:<Field label="条码内容"><textarea className="aiq-input" rows={5} value={lines} onChange={v=>setLines(v.target.value)}/></Field>}{order}<Field label="码制"><select className="aiq-select" value={options.barcodeFormat} onChange={v=>set('barcodeFormat',v.target.value as typeof options.barcodeFormat)}><option value="code128">Code 128</option><option value="ean13">EAN-13（自动校验）</option></select></Field><div className="wb-text-fields">{field('moduleWidth','模块宽度 mm')}{field('barHeight','条码高度 mm')}</div><Button disabled={e.busy} onClick={()=>void run(()=>({operation:'barcode',labels:(options.barcodeInput==='sequence'?values():lines.split(/\r?\n/).filter(s=>s.length)).map(t=>barcodePlan(t,options.barcodeFormat)),order:options.order,moduleWidth:num('moduleWidth')*72/25.4,height:num('barHeight')*72/25.4}))}>生成条码</Button></>}
 {op==='photoshop'&&<><p>直接选择链接的 PSD／PNG／JPG／TIF 图片。打开原图片，在 Photoshop 保存后回到这里更新。编辑原图会影响其他使用该文件的链接。</p><p>嵌入图先使用原生链接面板取消嵌入；本功能不转换整份矢量稿，也不自动保存 AI。</p><div className="aiq-row"><Button disabled={e.busy} onClick={()=>void run(()=>({operation:'photoshop',mode:'open'}))}>发送到 Photoshop</Button><Button disabled={e.busy} onClick={()=>void run(()=>({operation:'photoshop',mode:'update'}))}>更新所选图片</Button></div></>}
 </Card><EditorFeedback message={e.message} error={error||e.error}/>{rows.length>0&&<Card title="处理明细" icon="modules">{rows.map(r=><p key={r.index}>{r.label}：{r.detail}</p>)}</Card>}</>;
}
